# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74545603d920ddd0eff1a0532a0987e5cf614ab72fb84f7dc85b471ad16dacd8b49e20d07bb8eea7ffe7456b32a4a95a793c3ad9bc2653a9bf7c0a17bf5b028f

test:
  secret_key_base: ab535461963e2745cbb492a53a7dcd4d884f57f1adb169bdd161c4dc25ab9690be466477c8471d8d38dd90389c3cce250327e0f87c0fd2b3637bc17bde668d58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
